import { randomUUID } from 'node:crypto'
import bcrypt from 'bcryptjs'
import { afterEach, beforeEach, describe, expect, it } from 'vitest'
import type { FastifyInstance } from 'fastify'
import { StatusPagamento, StatusRodada, TipoParticipacao } from '@prisma/client'
import { buildApp, type AppDependencies } from '../src/app.js'
import type { AdminRepository } from '../src/modules/admins/admin.repository.js'
import type { JogadorCreateData, JogadorRepository, JogadorUpdateData } from '../src/modules/jogadores/jogador.repository.js'
import type { ParticipacaoCreateData, ParticipacaoUpdateData, RodadaCreateData, RodadaRecord, RodadaRepository, RodadaUpdateData } from '../src/modules/rodadas/rodada.repository.js'
import { SessionStore } from '../src/modules/auth/session.store.js'
import type { AdminEntity, JogadorEntity } from '../src/shared/entities.js'
import { AppError } from '../src/shared/errors.js'

class MemoryAdmins implements AdminRepository {
  constructor(public data: AdminEntity[]) {}
  async findByEmail(email: string) { return this.data.find((a) => a.email === email) ?? null }
  async findById(id: string) { return this.data.find((a) => a.id === id) ?? null }
}
class MemoryJogadores implements JogadorRepository {
  data: JogadorEntity[] = []
  async list(search?: string, onlyActive = false) { const q = search?.toLowerCase(); return this.data.filter((p) => (!onlyActive || p.ativo) && (!q || p.nome.toLowerCase().includes(q) || p.apelido.toLowerCase().includes(q))) }
  async findById(id: string) { return this.data.find((p) => p.id === id) ?? null }
  async create(input: JogadorCreateData) { const now = new Date(); const jogador = { id: randomUUID(), ...input, fotoUrl: input.fotoUrl ?? null, ativo: true, createdAt: now, updatedAt: now }; this.data.push(jogador); return jogador }
  async update(id: string, input: JogadorUpdateData) { const jogador = this.data.find((p) => p.id === id); if (!jogador) return null; Object.assign(jogador, input, { updatedAt: new Date() }); return jogador }
}
class MemoryRodadas implements RodadaRepository {
  data: RodadaRecord[] = []
  constructor(private jogadores: MemoryJogadores) {}
  async list() { return this.data }
  async findById(id: string) { return this.data.find((r) => r.id === id) ?? null }
  async findCurrent() { return this.data.find((r) => r.status === StatusRodada.PREPARACAO) ?? this.data.find((r) => r.status === StatusRodada.PLANEJADA) ?? null }
  async create(input: RodadaCreateData) { const now = new Date(); const rodada: RodadaRecord = { id: randomUUID(), data: new Date(`${input.data}T00:00:00Z`), horario: new Date(`1970-01-01T${input.horario}:00Z`), status: StatusRodada.PLANEJADA, valorJogadorLinha: input.valorJogadorLinha, createdAt: now, updatedAt: now, startedAt: null, endedAt: null, participacoes: [] }; this.data.push(rodada); return rodada }
  async update(id: string, input: RodadaUpdateData) { const r = this.need(id); this.mutable(r); if (input.valorJogadorLinha !== undefined) { if (r.participacoes.some((p) => p.pagamento?.status === StatusPagamento.PAGO)) throw new AppError(409, 'PAGAMENTO_PAGO', 'Pagamento pago'); r.valorJogadorLinha = input.valorJogadorLinha; r.participacoes.forEach((p) => { if (p.pagamento) p.pagamento.valor = input.valorJogadorLinha! }) } if (input.data) r.data = new Date(`${input.data}T00:00:00Z`); if (input.horario) r.horario = new Date(`1970-01-01T${input.horario}:00Z`); return r }
  async transition(id: string, from: StatusRodada, to: StatusRodada) { const r = this.need(id); if (r.status !== from) throw new AppError(409, 'TRANSICAO_INVALIDA', 'Status alterado'); if (to === StatusRodada.CANCELADA) { if (r.participacoes.some((p) => p.pagamento?.status === StatusPagamento.PAGO)) throw new AppError(409, 'PAGAMENTO_PAGO', 'Pagamento pago'); r.participacoes.forEach((p) => { p.pagamento = null }) } r.status = to; if (to === StatusRodada.ENCERRADA) r.endedAt = new Date(); return r }
  async addParticipacao(rodadaId: string, input: ParticipacaoCreateData, adminId: string) { const r = this.need(rodadaId); this.mutable(r); if (r.participacoes.some((p) => p.jogador.id === input.jogadorId)) throw new AppError(409, 'JOGADOR_JA_PARTICIPA', 'Duplicado'); const jogador = await this.jogadores.findById(input.jogadorId); if (!jogador) throw new AppError(404, 'NOT_FOUND', 'Jogador não encontrado'); const p: RodadaRecord['participacoes'][number] = { id: randomUUID(), tipo: input.tipo, confirmado: input.confirmado, presente: input.presente, ordemChegada: null, chegouEm: null, saiuEm: null, jogador, pagamento: null }; if (p.tipo === TipoParticipacao.LINHA && p.presente) p.pagamento = { id: randomUUID(), valor: r.valorJogadorLinha, status: StatusPagamento.PENDENTE, pagoEm: null }; r.participacoes.push(p); void adminId; return r }
  async addJogadorRapido(rodadaId: string, jogador: JogadorCreateData, participacao: Omit<ParticipacaoCreateData, 'jogadorId'>, adminId: string) { const novo = await this.jogadores.create(jogador); return this.addParticipacao(rodadaId, { jogadorId: novo.id, ...participacao }, adminId) }
  async updateParticipacao(id: string, input: ParticipacaoUpdateData) { const { r, p } = this.part(id); this.mutable(r); const tipo = input.tipo ?? p.tipo; const presente = input.presente ?? p.presente; const eligible = tipo === TipoParticipacao.LINHA && presente; if (!eligible && p.pagamento?.status === StatusPagamento.PAGO) throw new AppError(409, 'PAGAMENTO_PAGO', 'Pagamento pago'); Object.assign(p, input); if (eligible && !p.pagamento) p.pagamento = { id: randomUUID(), valor: r.valorJogadorLinha, status: StatusPagamento.PENDENTE, pagoEm: null }; if (!eligible) p.pagamento = null; return r }
  async removeParticipacao(id: string) { const { r, p } = this.part(id); this.mutable(r); if (p.pagamento?.status === StatusPagamento.PAGO) throw new AppError(409, 'PAGAMENTO_PAGO', 'Pagamento pago'); r.participacoes = r.participacoes.filter((item) => item.id !== id); return r }
  async updatePagamento(id: string, status: StatusPagamento) { for (const r of this.data) { const p = r.participacoes.find((item) => item.pagamento?.id === id); if (p?.pagamento) { this.mutable(r); p.pagamento.status = status; p.pagamento.pagoEm = status === StatusPagamento.PAGO ? new Date() : null; return r } } throw new AppError(404, 'NOT_FOUND', 'Pagamento não encontrado') }
  private need(id: string) { const r = this.data.find((item) => item.id === id); if (!r) throw new AppError(404, 'NOT_FOUND', 'Rodada não encontrada'); return r }
  private mutable(r: RodadaRecord) { if (r.status === StatusRodada.ENCERRADA || r.status === StatusRodada.CANCELADA) throw new AppError(409, 'RODADA_ENCERRADA', 'Somente leitura') }
  private part(id: string) { for (const r of this.data) { const p = r.participacoes.find((item) => item.id === id); if (p) return { r, p } } throw new AppError(404, 'NOT_FOUND', 'Participação não encontrada') }
}

describe('Etapa 2 - rodadas', () => {
  let app: FastifyInstance; let jogadores: MemoryJogadores; let rodadas: MemoryRodadas; let cookie: string; let jogador: JogadorEntity
  beforeEach(async () => {
    jogadores = new MemoryJogadores(); rodadas = new MemoryRodadas(jogadores); jogador = await jogadores.create({ nome: 'Daniel', apelido: 'Dani', telefone: '61999999999' })
    const admins = new MemoryAdmins([{ id: randomUUID(), nome: 'Admin', email: 'admin@futbrita.test', senhaHash: await bcrypt.hash('Senha123!', 4), ativo: true }])
    const deps: AppDependencies = { admins, jogadores, rodadas, sessions: new SessionStore(), databaseCheck: async () => undefined }
    app = await buildApp({ SESSION_SECRET: 'segredo-de-testes-com-mais-de-32-caracteres', NODE_ENV: 'test', WEB_ORIGIN: 'http://localhost:5173' }, deps)
    const login = await app.inject({ method: 'POST', url: '/api/auth/login', payload: { email: 'admin@futbrita.test', senha: 'Senha123!' } }); cookie = login.cookies.map((c) => `${c.name}=${c.value}`).join('; ')
  })
  afterEach(async () => app.close())
  const createRound = async (payload: Record<string, unknown> = { data: '2026-08-26' }) => app.inject({ method: 'POST', url: '/api/admin/rodadas', headers: { cookie }, payload })
  const add = async (roundId: string, payload: Record<string, unknown>) => app.inject({ method: 'POST', url: `/api/admin/rodadas/${roundId}/participantes`, headers: { cookie }, payload: { jogadorId: jogador.id, tipo: 'LINHA', confirmado: true, presente: false, ...payload } })

  it('cria rodada com status planejada', async () => { const r = await createRound(); expect(r.statusCode).toBe(201); expect(r.json().status).toBe('PLANEJADA') })
  it('aplica horário 20:00 e valor 11 por padrão', async () => { const r = await createRound(); expect(r.json()).toMatchObject({ horario: '20:00', valorJogadorLinha: 11 }) })
  it('edita dados da rodada', async () => { const r = await createRound(); const updated = await app.inject({ method: 'PATCH', url: `/api/admin/rodadas/${r.json().id}`, headers: { cookie }, payload: { horario: '21:00', valorJogadorLinha: 12 } }); expect(updated.json()).toMatchObject({ horario: '21:00', valorJogadorLinha: 12 }) })
  it('aceita transição PLANEJADA para PREPARACAO', async () => { const r = await createRound(); const updated = await app.inject({ method: 'PATCH', url: `/api/admin/rodadas/${r.json().id}`, headers: { cookie }, payload: { status: 'PREPARACAO' } }); expect(updated.json().status).toBe('PREPARACAO') })
  it('rejeita transição arbitrária para ENCERRADA', async () => { const r = await createRound(); const updated = await app.inject({ method: 'PATCH', url: `/api/admin/rodadas/${r.json().id}`, headers: { cookie }, payload: { status: 'ENCERRADA' } }); expect(updated.statusCode).toBe(409); expect(updated.json().error).toBe('TRANSICAO_INVALIDA') })
  it('encerra após preparação e torna somente leitura', async () => { const r = await createRound(); await app.inject({ method: 'PATCH', url: `/api/admin/rodadas/${r.json().id}`, headers: { cookie }, payload: { status: 'PREPARACAO' } }); const closed = await app.inject({ method: 'PATCH', url: `/api/admin/rodadas/${r.json().id}`, headers: { cookie }, payload: { status: 'ENCERRADA' } }); expect(closed.json().endedAt).toBeTruthy(); const denied = await add(r.json().id, {}); expect(denied.statusCode).toBe(409) })
  it('cancela rodada planejada', async () => { const r = await createRound(); const cancelled = await app.inject({ method: 'PATCH', url: `/api/admin/rodadas/${r.json().id}`, headers: { cookie }, payload: { status: 'CANCELADA' } }); expect(cancelled.json().status).toBe('CANCELADA') })
  it('adiciona jogador existente de linha', async () => { const r = await createRound(); const response = await add(r.json().id, {}); expect(response.statusCode).toBe(201); expect(response.json().participacoes[0]).toMatchObject({ tipo: 'LINHA', presente: false }) })
  it('impede jogador duplicado na rodada', async () => { const r = await createRound(); await add(r.json().id, {}); const duplicate = await add(r.json().id, {}); expect(duplicate.statusCode).toBe(409); expect(duplicate.json().error).toBe('JOGADOR_JA_PARTICIPA') })
  it('adiciona goleiro sem cobrança', async () => { const r = await createRound(); const response = await add(r.json().id, { tipo: 'GOLEIRO', presente: true }); expect(response.json().participacoes[0].pagamento).toBeNull() })
  it('linha ausente não gera cobrança', async () => { const r = await createRound(); const response = await add(r.json().id, { presente: false }); expect(response.json().participacoes[0].pagamento).toBeNull() })
  it('linha presente gera cobrança pendente', async () => { const r = await createRound(); const response = await add(r.json().id, { presente: true }); expect(response.json().participacoes[0].pagamento).toMatchObject({ valor: 11, status: 'PENDENTE' }) })
  it('marcar presença repetidamente não duplica cobrança', async () => { const r = await createRound(); const added = await add(r.json().id, { presente: true }); const p = added.json().participacoes[0]; await app.inject({ method: 'PATCH', url: `/api/admin/participacoes/${p.id}`, headers: { cookie }, payload: { presente: true } }); const current = await app.inject({ method: 'GET', url: `/api/admin/rodadas/${r.json().id}`, headers: { cookie } }); expect(current.json().participacoes.filter((x: any) => x.pagamento)).toHaveLength(1) })
  it('linha presente para goleiro remove cobrança pendente', async () => { const r = await createRound(); const added = await add(r.json().id, { presente: true }); const changed = await app.inject({ method: 'PATCH', url: `/api/admin/participacoes/${added.json().participacoes[0].id}`, headers: { cookie }, payload: { tipo: 'GOLEIRO' } }); expect(changed.json().participacoes[0].pagamento).toBeNull() })
  it('goleiro presente para linha cria cobrança', async () => { const r = await createRound(); const added = await add(r.json().id, { tipo: 'GOLEIRO', presente: true }); const changed = await app.inject({ method: 'PATCH', url: `/api/admin/participacoes/${added.json().participacoes[0].id}`, headers: { cookie }, payload: { tipo: 'LINHA' } }); expect(changed.json().participacoes[0].pagamento.valor).toBe(11) })
  it('linha presente para ausente remove cobrança pendente', async () => { const r = await createRound(); const added = await add(r.json().id, { presente: true }); const changed = await app.inject({ method: 'PATCH', url: `/api/admin/participacoes/${added.json().participacoes[0].id}`, headers: { cookie }, payload: { presente: false } }); expect(changed.json().participacoes[0].pagamento).toBeNull() })
  it('marca pagamento como pago e permite correção para pendente', async () => { const r = await createRound(); const added = await add(r.json().id, { presente: true }); const payment = added.json().participacoes[0].pagamento; const paid = await app.inject({ method: 'PATCH', url: `/api/admin/pagamentos/${payment.id}`, headers: { cookie }, payload: { status: 'PAGO' } }); expect(paid.json().participacoes[0].pagamento.pagoEm).toBeTruthy(); const pending = await app.inject({ method: 'PATCH', url: `/api/admin/pagamentos/${payment.id}`, headers: { cookie }, payload: { status: 'PENDENTE' } }); expect(pending.json().participacoes[0].pagamento.pagoEm).toBeNull() })
  it('bloqueia remoção de obrigação já paga', async () => { const r = await createRound(); const added = await add(r.json().id, { presente: true }); const p = added.json().participacoes[0]; await app.inject({ method: 'PATCH', url: `/api/admin/pagamentos/${p.pagamento.id}`, headers: { cookie }, payload: { status: 'PAGO' } }); const denied = await app.inject({ method: 'PATCH', url: `/api/admin/participacoes/${p.id}`, headers: { cookie }, payload: { presente: false } }); expect(denied.statusCode).toBe(409); expect(denied.json().error).toBe('PAGAMENTO_PAGO') })
  it('remove participante sem pagamento pago', async () => { const r = await createRound(); const added = await add(r.json().id, {}); const removed = await app.inject({ method: 'DELETE', url: `/api/admin/participacoes/${added.json().participacoes[0].id}`, headers: { cookie } }); expect(removed.json().participacoes).toHaveLength(0) })
  it('cadastro rápido cria jogador, participação e cobrança atomicamente', async () => { const r = await createRound(); const response = await app.inject({ method: 'POST', url: `/api/admin/rodadas/${r.json().id}/participantes/novo-jogador`, headers: { cookie }, payload: { nome: 'Novo', apelido: 'Novato', telefone: '(61) 98888-7777', tipo: 'LINHA', presente: true } }); expect(response.statusCode).toBe(201); expect(response.json().participacoes[0]).toMatchObject({ jogador: { apelido: 'Novato' }, pagamento: { valor: 11 } }); expect(jogadores.data.some((p) => p.apelido === 'Novato')).toBe(true) })
  it('calcula resumo financeiro sem goleiros', async () => { const r = await createRound(); const line = await add(r.json().id, { presente: true }); const payment = line.json().participacoes[0].pagamento; const keeper = await jogadores.create({ nome: 'Goleiro', apelido: 'GK', telefone: '61988887777' }); await app.inject({ method: 'POST', url: `/api/admin/rodadas/${r.json().id}/participantes`, headers: { cookie }, payload: { jogadorId: keeper.id, tipo: 'GOLEIRO', confirmado: true, presente: true } }); await app.inject({ method: 'PATCH', url: `/api/admin/pagamentos/${payment.id}`, headers: { cookie }, payload: { status: 'PAGO' } }); const financial = await app.inject({ method: 'GET', url: `/api/admin/rodadas/${r.json().id}/financeiro`, headers: { cookie } }); expect(financial.json()).toMatchObject({ linhasPresentes: 1, goleirosPresentes: 1, totalPrevisto: 11, totalRecebido: 11, totalPendente: 0 }) })
  it('área pública nunca expõe telefone ou financeiro', async () => { const r = await createRound(); await add(r.json().id, { presente: true }); const response = await app.inject({ method: 'GET', url: '/api/public/rodadas/atual' }); expect(response.statusCode).toBe(200); expect(response.body).not.toContain('telefone'); expect(response.body).not.toContain('pagamento'); expect(response.body).not.toContain('valorJogadorLinha'); expect(response.body).not.toContain('totalPendente') })
})
