import { describe, expect, it } from 'vitest'
import { buildRanking, calculatePlayerStats, type StatisticMatch, type StatisticPlayer } from '../src/domain/statistics/statistics-engine.js'

const player = (id: string, apelido = id): StatisticPlayer => ({ id, nome: `Nome ${id}`, apelido, ativo: true })
const match = (id: string, number: number, result: 'TIME_1' | 'TIME_2' | 'EMPATE', winner: 'TIME_1' | 'TIME_2' | null, goals: string[] = [], roundId = 'r1', date = '2026-08-01'): StatisticMatch => ({ id, roundId, date, number, result, winner, score1: goals.length, score2: 0, lineups: [{ playerId: 'a', side: 'TIME_1' }, { playerId: 'b', side: 'TIME_2' }], goals: goals.map((playerId) => ({ playerId, side: playerId === 'a' ? 'TIME_1' : 'TIME_2' })) })

describe('motor derivado de estatísticas', () => {
  it('retorna zeros seguros para jogador sem partidas', () => expect(calculatePlayerStats(player('a'), [], []).metrics).toMatchObject({ games: 0, goals: 0, goalAverage: 0, winRate: 0, currentStreak: 0, bestStreak: 0 }))
  it('calcula vitória, derrota e empate sem transformar saída operacional em derrota', () => { const matches = [match('1', 1, 'TIME_1', 'TIME_1'), match('2', 2, 'EMPATE', null), match('3', 3, 'TIME_2', 'TIME_2')]; expect(calculatePlayerStats(player('a'), matches, []).metrics).toMatchObject({ games: 3, wins: 1, draws: 1, losses: 1, points: 4, winRate: 44.44 }) })
  it('deriva gols, média e alterações dos eventos', () => { const stats = calculatePlayerStats(player('a'), [match('1', 1, 'TIME_1', 'TIME_1', ['a', 'a']), match('2', 2, 'TIME_1', 'TIME_1', ['a'])], []).metrics; expect(stats).toMatchObject({ games: 2, goals: 3, goalAverage: 1.5 }) })
  it('calcula sequência atual e maior sequência', () => { const results = [['TIME_1', 'TIME_1'], ['TIME_1', 'TIME_1'], ['TIME_2', 'TIME_2'], ['TIME_1', 'TIME_1'], ['TIME_1', 'TIME_1'], ['TIME_1', 'TIME_1'], ['EMPATE', null], ['TIME_1', 'TIME_1']] as const; const stats = calculatePlayerStats(player('a'), results.map(([result, winner], index) => match(String(index), index + 1, result, winner)), []).metrics; expect(stats).toMatchObject({ currentStreak: 1, bestStreak: 3 }) })
  it('conta presença uma vez por rodada mesmo com várias partidas', () => { const appearances = Array.from({ length: 10 }, () => ({ playerId: 'a', roundId: 'r1', date: '2026-08-01' })); expect(calculatePlayerStats(player('a'), [], appearances).metrics.appearances).toBe(1) })
  it('ordena artilharia por gols, média, vitórias e nome', () => { const base = (id: string, apelido: string, goals: number) => ({ ...calculatePlayerStats(player(id, apelido), [], []).metrics, games: 10, goals, goalAverage: goals / 10, wins: 5 }); const metrics = [base('d', 'Daniel', 10), base('p', 'Pedro', 8), base('j', 'João', 12)]; expect(buildRanking(metrics, 'goals').map((item) => item.player.apelido)).toEqual(['João', 'Daniel', 'Pedro']) })
  it('desempata artilharia por média', () => { const a = { ...calculatePlayerStats(player('a'), [], []).metrics, goals: 10, games: 5, goalAverage: 2, wins: 1 }; const b = { ...calculatePlayerStats(player('b'), [], []).metrics, goals: 10, games: 10, goalAverage: 1, wins: 8 }; expect(buildRanking([b, a], 'goals')[0].player.id).toBe('a') })
  it('distingue mais vitórias de melhor aproveitamento', () => { const many = { ...calculatePlayerStats(player('a'), [], []).metrics, games: 10, wins: 8, winRate: 80 }; const perfect = { ...calculatePlayerStats(player('b'), [], []).metrics, games: 2, wins: 2, winRate: 100 }; expect(buildRanking([perfect, many], 'wins')[0].player.id).toBe('a'); expect(buildRanking([many, perfect], 'winRate')[0].player.id).toBe('b') })
  it('ordena média de gols matematicamente', () => { const a = { ...calculatePlayerStats(player('a'), [], []).metrics, games: 5, goals: 5, goalAverage: 1 }; const b = { ...calculatePlayerStats(player('b'), [], []).metrics, games: 10, goals: 8, goalAverage: .8 }; expect(buildRanking([b, a], 'goalAverage')[0].player.id).toBe('a') })
})
