import { ArrowLeft, Check, CircleDollarSign, Pencil, Plus, Search, ShieldCheck, Trash2, UserPlus, Users, X } from 'lucide-react'
import { useCallback, useEffect, useMemo, useState, type FormEvent } from 'react'
import { Link, useParams } from 'react-router-dom'
import type { JogadorAdmin, ParticipacaoAdmin, RodadaAdmin, TipoParticipacao } from '@fut-brita/shared'
import { api } from '../../services/api'
import { Button } from '../../components/ui/Button'
import { EmptyState, ErrorState, Loading } from '../../components/ui/States'
import { Modal } from '../../components/ui/Modal'
import { Input } from '../../components/ui/Input'
import { Toast } from '../../components/ui/Toast'
import { dateBr, money, statusClass, statusLabel } from '../../utils/format'
import { GameOperations } from './GameOperations'

type Filter = 'TODOS' | 'PRESENTES' | 'AUSENTES' | 'LINHA' | 'GOLEIRO' | 'PENDENTES' | 'PAGOS'
type ModalType = 'existing' | 'quick' | 'edit' | null
const filters: Array<{ id: Filter; label: string }> = [{ id: 'TODOS', label: 'Todos' }, { id: 'PRESENTES', label: 'Presentes' }, { id: 'AUSENTES', label: 'Ausentes' }, { id: 'LINHA', label: 'Linha' }, { id: 'GOLEIRO', label: 'Goleiros' }, { id: 'PENDENTES', label: 'Pendentes' }, { id: 'PAGOS', label: 'Pagos' }]
const phoneMask = (value: string) => { const digits = value.replace(/\D/g, '').slice(0, 11); if (digits.length <= 2) return digits; if (digits.length <= 6) return `(${digits.slice(0, 2)}) ${digits.slice(2)}`; if (digits.length <= 10) return `(${digits.slice(0, 2)}) ${digits.slice(2, 6)}-${digits.slice(6)}`; return `(${digits.slice(0, 2)}) ${digits.slice(2, 7)}-${digits.slice(7)}` }

export function AdminRodadaDetailPage() {
  const { id } = useParams(); const [round, setRound] = useState<RodadaAdmin | null>(null); const [players, setPlayers] = useState<JogadorAdmin[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [filter, setFilter] = useState<Filter>('TODOS'); const [modal, setModal] = useState<ModalType>(null); const [busy, setBusy] = useState(false); const [toast, setToast] = useState<{ message: string; kind?: 'success' | 'error' } | null>(null); const [selectedPlayer, setSelectedPlayer] = useState(''); const [tipo, setTipo] = useState<TipoParticipacao>('LINHA'); const [presente, setPresente] = useState(false); const [quick, setQuick] = useState({ nome: '', apelido: '', telefone: '' }); const [search, setSearch] = useState(''); const [edit, setEdit] = useState({ data: '', horario: '', valorJogadorLinha: '11.00' })
  const load = useCallback(async () => { if (!id) return; setLoading(true); setError(''); try { const [roundData, playersData] = await Promise.all([api<RodadaAdmin>(`/admin/rodadas/${id}`), api<JogadorAdmin[]>('/admin/jogadores')]); setRound(roundData); setPlayers(playersData.filter((p) => p.ativo)) } catch (e) { setError(e instanceof Error ? e.message : 'Não foi possível carregar a rodada') } finally { setLoading(false) } }, [id])
  useEffect(() => { void load() }, [load]); useEffect(() => { if (!toast) return; const timer = setTimeout(() => setToast(null), 3500); return () => clearTimeout(timer) }, [toast])
  const mutate = async (path: string, method: string, body?: unknown, success?: string) => { setBusy(true); try { const updated = await api<RodadaAdmin>(path, { method, ...(body !== undefined ? { body: JSON.stringify(body) } : {}) }); setRound(updated); if (success) setToast({ message: success }) } catch (e) { setToast({ message: e instanceof Error ? e.message : 'Ação não concluída', kind: 'error' }) } finally { setBusy(false) } }
  const readOnly = round?.status === 'ENCERRADA' || round?.status === 'CANCELADA'
  const visible = useMemo(() => (round?.participacoes ?? []).filter((p) => filter === 'TODOS' || (filter === 'PRESENTES' && p.presente) || (filter === 'AUSENTES' && !p.presente) || (filter === 'LINHA' && p.tipo === 'LINHA') || (filter === 'GOLEIRO' && p.tipo === 'GOLEIRO') || (filter === 'PENDENTES' && p.pagamento?.status === 'PENDENTE') || (filter === 'PAGOS' && p.pagamento?.status === 'PAGO')), [round, filter])
  const availablePlayers = useMemo(() => { const participating = new Set(round?.participacoes.map((p) => p.jogador.id)); const q = search.trim().toLocaleLowerCase('pt-BR'); return players.filter((p) => !participating.has(p.id) && (!q || p.nome.toLocaleLowerCase('pt-BR').includes(q) || p.apelido.toLocaleLowerCase('pt-BR').includes(q))) }, [players, round, search])
  const openEdit = () => { if (!round) return; setEdit({ data: round.data, horario: round.horario, valorJogadorLinha: round.valorJogadorLinha.toFixed(2) }); setModal('edit') }
  const addExisting = async (event: FormEvent) => { event.preventDefault(); if (!id || !selectedPlayer) return; await mutate(`/admin/rodadas/${id}/participantes`, 'POST', { jogadorId: selectedPlayer, tipo, confirmado: true, presente }, 'Participante adicionado.'); setModal(null); setSelectedPlayer(''); setPresente(false) }
  const addQuick = async (event: FormEvent) => { event.preventDefault(); if (!id) return; await mutate(`/admin/rodadas/${id}/participantes/novo-jogador`, 'POST', { ...quick, tipo, confirmado: true, presente }, 'Jogador cadastrado e adicionado.'); setModal(null); setQuick({ nome: '', apelido: '', telefone: '' }); setPresente(true) }
  const saveEdit = async (event: FormEvent) => { event.preventDefault(); if (!id) return; await mutate(`/admin/rodadas/${id}`, 'PATCH', { data: edit.data, horario: edit.horario, valorJogadorLinha: Number(edit.valorJogadorLinha) }, 'Rodada atualizada.'); setModal(null) }
  const transition = async (status: 'PREPARACAO' | 'ENCERRADA' | 'CANCELADA') => { if (!id) return; const action = status === 'CANCELADA' ? 'cancelar' : status === 'ENCERRADA' ? 'encerrar' : 'iniciar a preparação de'; if (!window.confirm(`Deseja ${action} esta rodada?`)) return; await mutate(`/admin/rodadas/${id}`, 'PATCH', { status }, `Rodada: ${statusLabel[status]}.`) }
  const patchParticipant = (p: ParticipacaoAdmin, body: unknown, success: string) => mutate(`/admin/participacoes/${p.id}`, 'PATCH', body, success)
  if (loading) return <div className="page-shell py-8"><Loading /></div>
  if (error || !round) return <div className="page-shell py-8"><ErrorState message={error || 'Rodada não encontrada'} retry={load} /></div>
  return <div className="page-shell py-6 sm:py-10"><Link to="/admin/rodadas" className="inline-flex min-h-12 items-center gap-2 text-sm font-bold text-neutral-400"><ArrowLeft size={19} />Rodadas</Link><header className="surface mt-3 p-5 sm:p-7"><div className="flex flex-col gap-5 lg:flex-row lg:items-start lg:justify-between"><div><div className="flex flex-wrap items-center gap-2"><span className={`rounded-full px-3 py-1 text-xs font-bold uppercase ${statusClass[round.status]}`}>{statusLabel[round.status]}</span><span className="text-sm text-neutral-500">{round.horario} · {money(round.valorJogadorLinha)} por linha</span></div><h1 className="mt-4 text-3xl font-black capitalize tracking-tight sm:text-4xl">{dateBr(round.data)}</h1></div>{!readOnly && <div className="grid grid-cols-2 gap-2 sm:flex">{round.status === 'PLANEJADA' && <Button onClick={() => void transition('PREPARACAO')} disabled={busy}><Check size={18} />Preparar</Button>}{round.status === 'PREPARACAO' && <Button onClick={() => void transition('ENCERRADA')} disabled={busy}><Check size={18} />Encerrar</Button>}<Button variant="secondary" onClick={openEdit} disabled={busy}><Pencil size={17} />Editar</Button><Button variant="danger" className="col-span-2" onClick={() => void transition('CANCELADA')} disabled={busy}><X size={18} />Cancelar</Button></div>}</div></header>
    <section aria-label="Resumo da rodada" className="mt-4 grid grid-cols-2 gap-3 lg:grid-cols-6">{[
      ['Participantes', round.resumo.totalParticipantes], ['Linhas presentes', round.resumo.linhasPresentes], ['Goleiros', round.resumo.goleirosPresentes], ['Ausentes', round.resumo.ausentes], ['Recebido', money(round.resumo.totalRecebido)], ['Pendente', money(round.resumo.totalPendente)],
    ].map(([label, value]) => <article key={label} className="surface min-w-0 p-4"><p className="break-words text-xs font-bold uppercase tracking-wide text-neutral-500">{label}</p><p className="mt-2 break-words text-xl font-black">{value}</p></article>)}</section>
    <GameOperations round={round} onRoundChanged={load} />
    <section className="mt-9"><div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-brita-500">NO CAMPO</p><h2 className="mt-2 text-2xl font-black">Participantes</h2></div>{!readOnly && <div className="grid grid-cols-2 gap-2"><Button variant="secondary" onClick={() => { setTipo('LINHA'); setPresente(false); setModal('existing') }}><Plus size={18} />Existente</Button><Button onClick={() => { setTipo('LINHA'); setPresente(true); setModal('quick') }}><UserPlus size={18} />Novo</Button></div>}</div><div className="mt-5 flex flex-wrap gap-2" aria-label="Filtros">{filters.map((item) => <button key={item.id} onClick={() => setFilter(item.id)} className={`min-h-11 rounded-xl px-4 text-sm font-bold transition ${filter === item.id ? 'bg-brita-500 text-black' : 'border border-white/10 bg-white/5 text-neutral-400'}`}>{item.label}</button>)}</div><div className="mt-5">{visible.length === 0 ? <EmptyState title="Nenhum participante neste filtro" description={round.participacoes.length ? 'Escolha outro filtro para continuar.' : 'Adicione jogadores existentes ou faça um cadastro rápido.'} /> : <div className="grid gap-3 xl:grid-cols-2">{visible.map((p) => <ParticipantCard key={p.id} participant={p} readOnly={!!readOnly} busy={busy} onPatch={patchParticipant} onPayment={(status) => mutate(`/admin/pagamentos/${p.pagamento!.id}`, 'PATCH', { status }, status === 'PAGO' ? 'Pagamento confirmado.' : 'Pagamento voltou para pendente.')} onRemove={() => { if (window.confirm(`Remover ${p.jogador.apelido} desta rodada?`)) void mutate(`/admin/participacoes/${p.id}`, 'DELETE', undefined, 'Participante removido.') }} />)}</div>}</div></section>
    {modal === 'existing' && <Modal title="Adicionar participante" onClose={() => setModal(null)}><form onSubmit={addExisting} className="space-y-5"><div><label className="label" htmlFor="player-search">Buscar jogador</label><div className="relative"><Search className="absolute left-4 top-1/2 -translate-y-1/2 text-neutral-500" size={19} /><input id="player-search" className="field pl-11" value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Nome ou apelido" /></div></div><div><label className="label" htmlFor="jogador">Jogador</label><select id="jogador" className="field" value={selectedPlayer} onChange={(e) => setSelectedPlayer(e.target.value)} required><option value="">Selecione</option>{availablePlayers.map((p) => <option key={p.id} value={p.id}>{p.apelido} — {p.nome}</option>)}</select></div><ParticipationFields tipo={tipo} setTipo={setTipo} presente={presente} setPresente={setPresente} /><Button type="submit" className="w-full" disabled={busy || !selectedPlayer}>{busy ? 'Adicionando...' : 'Adicionar à rodada'}</Button></form></Modal>}
    {modal === 'quick' && <Modal title="Novo jogador na rodada" onClose={() => setModal(null)}><form onSubmit={addQuick} className="space-y-5"><Input label="Nome" name="quick-nome" value={quick.nome} onChange={(e) => setQuick({ ...quick, nome: e.target.value })} required /><Input label="Apelido" name="quick-apelido" value={quick.apelido} onChange={(e) => setQuick({ ...quick, apelido: e.target.value })} required /><Input label="Telefone" name="quick-telefone" type="tel" inputMode="tel" value={quick.telefone} onChange={(e) => setQuick({ ...quick, telefone: phoneMask(e.target.value) })} placeholder="(61) 99999-9999" required /><ParticipationFields tipo={tipo} setTipo={setTipo} presente={presente} setPresente={setPresente} /><Button type="submit" className="w-full" disabled={busy}>{busy ? 'Salvando...' : 'Salvar e adicionar'}</Button></form></Modal>}
    {modal === 'edit' && <Modal title="Editar rodada" onClose={() => setModal(null)}><form onSubmit={saveEdit} className="space-y-5"><Input label="Data" type="date" name="edit-data" value={edit.data} onChange={(e) => setEdit({ ...edit, data: e.target.value })} required /><Input label="Horário" type="time" name="edit-horario" value={edit.horario} onChange={(e) => setEdit({ ...edit, horario: e.target.value })} required /><Input label="Valor por jogador de linha" type="number" inputMode="decimal" step="0.01" min="0.01" name="edit-valor" value={edit.valorJogadorLinha} onChange={(e) => setEdit({ ...edit, valorJogadorLinha: e.target.value })} required /><Button type="submit" className="w-full" disabled={busy}>Salvar alterações</Button></form></Modal>}
    {toast && <Toast {...toast} />}
  </div>
}

function ParticipationFields({ tipo, setTipo, presente, setPresente }: { tipo: TipoParticipacao; setTipo: (value: TipoParticipacao) => void; presente: boolean; setPresente: (value: boolean) => void }) {
  return <><fieldset><legend className="label">Tipo na rodada</legend><div className="grid grid-cols-2 gap-2"><button type="button" onClick={() => setTipo('LINHA')} className={`min-h-12 rounded-xl border font-bold ${tipo === 'LINHA' ? 'border-brita-500 bg-brita-500/15 text-brita-400' : 'border-white/10 text-neutral-400'}`}><Users className="mx-auto mb-1" size={18} />Linha</button><button type="button" onClick={() => setTipo('GOLEIRO')} className={`min-h-12 rounded-xl border font-bold ${tipo === 'GOLEIRO' ? 'border-brita-500 bg-brita-500/15 text-brita-400' : 'border-white/10 text-neutral-400'}`}><ShieldCheck className="mx-auto mb-1" size={18} />Goleiro</button></div></fieldset><label className="flex min-h-14 cursor-pointer items-center justify-between rounded-xl border border-white/10 p-4"><span><strong className="block text-sm">Já está presente?</strong><span className="text-xs text-neutral-500">Gera cobrança somente para Linha.</span></span><input type="checkbox" className="size-6 accent-orange-500" checked={presente} onChange={(e) => setPresente(e.target.checked)} /></label></>
}

function ParticipantCard({ participant: p, readOnly, busy, onPatch, onPayment, onRemove }: { participant: ParticipacaoAdmin; readOnly: boolean; busy: boolean; onPatch: (p: ParticipacaoAdmin, body: unknown, message: string) => Promise<void>; onPayment: (status: 'PENDENTE' | 'PAGO') => Promise<void>; onRemove: () => void }) {
  return <article className={`surface overflow-hidden ${!p.presente ? 'opacity-75' : ''}`}><div className="flex min-w-0 items-start gap-3 p-4 sm:p-5"><span className={`grid size-12 shrink-0 place-items-center rounded-xl ${p.tipo === 'GOLEIRO' ? 'bg-sky-500/10 text-sky-400' : 'bg-brita-500/10 text-brita-500'}`}>{p.tipo === 'GOLEIRO' ? <ShieldCheck /> : <Users />}</span><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><h3 className="truncate font-black">{p.jogador.apelido}</h3><span className={`rounded-full px-2 py-1 text-[10px] font-bold uppercase ${p.presente ? 'bg-emerald-500/10 text-emerald-400' : 'bg-neutral-700 text-neutral-400'}`}>{p.presente ? 'Presente' : 'Ausente'}</span></div><p className="mt-1 truncate text-sm text-neutral-500">{p.jogador.nome}</p><p className="mt-2 text-sm font-bold">{p.tipo === 'GOLEIRO' ? 'Isento' : p.pagamento ? `${money(p.pagamento.valor)} · ${p.pagamento.status === 'PAGO' ? 'Pago' : 'Pendente'}` : 'R$ 0,00 · Sem cobrança'}</p></div>{!readOnly && <button onClick={onRemove} disabled={busy} aria-label={`Remover ${p.jogador.apelido}`} className="grid size-11 shrink-0 place-items-center rounded-xl text-neutral-600 hover:bg-red-500/10 hover:text-red-400"><Trash2 size={18} /></button>}</div>{!readOnly && <div className="grid grid-cols-2 gap-2 border-t border-white/5 p-3 sm:grid-cols-3"><Button variant="secondary" onClick={() => void onPatch(p, { presente: !p.presente }, p.presente ? 'Marcado ausente.' : 'Presença confirmada.')} disabled={busy}>{p.presente ? <X size={17} /> : <Check size={17} />}{p.presente ? 'Ausente' : 'Presente'}</Button><Button variant="secondary" onClick={() => void onPatch(p, { tipo: p.tipo === 'LINHA' ? 'GOLEIRO' : 'LINHA' }, `Agora é ${p.tipo === 'LINHA' ? 'goleiro' : 'linha'}.`)} disabled={busy}>{p.tipo === 'LINHA' ? <ShieldCheck size={17} /> : <Users size={17} />}{p.tipo === 'LINHA' ? 'Goleiro' : 'Linha'}</Button>{p.pagamento && <Button className="col-span-2 sm:col-span-1" variant={p.pagamento.status === 'PAGO' ? 'secondary' : 'primary'} onClick={() => void onPayment(p.pagamento!.status === 'PAGO' ? 'PENDENTE' : 'PAGO')} disabled={busy}><CircleDollarSign size={17} />{p.pagamento.status === 'PAGO' ? 'Pendente' : 'Marcar pago'}</Button>}</div>}</article>
}
