import { ArrowDown, ArrowUp, LogOut, Play, Radio, UserCheck, Users } from 'lucide-react'
import { useCallback, useEffect, useMemo, useState } from 'react'
import { Link } from 'react-router-dom'
import type { ChegadaJogador, EstadoJogo, RodadaAdmin } from '@fut-brita/shared'
import { api } from '../../services/api'
import { Button } from '../../components/ui/Button'
import { EmptyState, Loading } from '../../components/ui/States'

export function GameOperations({ round, onRoundChanged }: { round: RodadaAdmin; onRoundChanged: () => Promise<void> }) {
  const [arrivals, setArrivals] = useState<ChegadaJogador[]>([]); const [game, setGame] = useState<EstadoJogo | null>(null); const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const [loading, setLoading] = useState(true)
  const load = useCallback(async () => { try { setError(''); const [arrivalData, gameData] = await Promise.all([api<ChegadaJogador[]>(`/admin/rodadas/${round.id}/chegadas`), api<EstadoJogo | null>(`/admin/rodadas/${round.id}/estado-jogo`)]); setArrivals(arrivalData); setGame(gameData) } catch (e) { setError(e instanceof Error ? e.message : 'Não foi possível carregar o motor') } finally { setLoading(false) } }, [round.id])
  useEffect(() => { void load() }, [load])
  const arrived = useMemo(() => new Set(arrivals.map((item) => item.participacaoId)), [arrivals])
  const waiting = round.participacoes.filter((p) => p.tipo === 'LINHA' && p.presente && !p.saiuEm && !arrived.has(p.id))
  const action = async (path: string, method: string, body?: unknown, refreshRound = false) => { setBusy(true); setError(''); try { await api(path, { method, ...(body === undefined ? {} : { body: JSON.stringify(body) }) }); await load(); if (refreshRound) await onRoundChanged() } catch (e) { setError(e instanceof Error ? e.message : 'Ação não concluída') } finally { setBusy(false) } }
  const move = (index: number, delta: number) => { const next = [...arrivals]; const target = index + delta; if (target < 0 || target >= next.length) return; [next[index], next[target]] = [next[target], next[index]]; void action(`/admin/rodadas/${round.id}/chegadas/reordenar`, 'PUT', { participacaoIds: next.map((item) => item.participacaoId) }) }
  const canOperate = round.status === 'PREPARACAO' || round.status === 'EM_ANDAMENTO'
  return <section className="mt-9" aria-labelledby="game-title"><div className="flex flex-col gap-2 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-brita-500">OPERAÇÃO DE CAMPO</p><h2 id="game-title" className="mt-2 text-2xl font-black">Chegada, times e fila</h2></div>{game && <span className="rounded-full border border-white/10 px-3 py-2 text-sm font-bold text-neutral-400">Ciclo {game.ciclo}</span>}</div>
    {error && <p role="alert" className="mt-4 rounded-xl border border-red-500/30 bg-red-500/10 p-3 text-sm text-red-300">{error}</p>}
    {loading ? <div className="mt-4"><Loading /></div> : <>
      {!game && <div className="mt-5 grid gap-4 lg:grid-cols-2"><article className="surface p-4 sm:p-5"><h3 className="font-black">Ainda não chegaram <span className="text-neutral-500">({waiting.length})</span></h3><div className="mt-3 space-y-2">{waiting.map((p) => <button key={p.id} disabled={!canOperate || busy} onClick={() => void action(`/admin/rodadas/${round.id}/chegadas`, 'POST', { participacaoId: p.id })} className="flex min-h-14 w-full items-center gap-3 rounded-xl border border-white/10 px-4 text-left font-bold hover:border-brita-500/50 disabled:opacity-50"><UserCheck className="text-brita-500" size={20}/><span className="min-w-0 flex-1 truncate">{p.jogador.apelido}</span><span className="text-xs text-neutral-500">Marcar chegou</span></button>)}{!waiting.length && <p className="py-4 text-sm text-neutral-500">Todos os linhas presentes já receberam chegada.</p>}</div></article>
      <article className="surface p-4 sm:p-5"><h3 className="font-black">Ordem registrada <span className="text-neutral-500">({arrivals.length})</span></h3><div className="mt-3 space-y-2">{arrivals.map((item, index) => <div key={item.participacaoId} className="flex min-h-14 items-center gap-2 rounded-xl bg-white/[.03] px-3"><span className="grid size-9 shrink-0 place-items-center rounded-lg bg-brita-500 font-black text-black">{index + 1}</span><span className="min-w-0 flex-1 truncate font-bold">{item.apelido}</span><button aria-label={`Subir ${item.apelido}`} disabled={busy || index === 0} onClick={() => move(index, -1)} className="grid size-11 place-items-center rounded-lg text-neutral-400 disabled:opacity-20"><ArrowUp size={18}/></button><button aria-label={`Descer ${item.apelido}`} disabled={busy || index === arrivals.length - 1} onClick={() => move(index, 1)} className="grid size-11 place-items-center rounded-lg text-neutral-400 disabled:opacity-20"><ArrowDown size={18}/></button><button aria-label={`Remover chegada de ${item.apelido}`} disabled={busy} onClick={() => void action(`/admin/rodadas/${round.id}/chegadas/${item.participacaoId}`, 'DELETE')} className="grid size-11 place-items-center rounded-lg text-red-400"><LogOut size={17}/></button></div>)}</div>{arrivals.length < 12 && <p className="mt-4 text-sm text-amber-300">São necessários pelo menos 12 jogadores de linha para formar os dois times.</p>}{round.status === 'PREPARACAO' && <Button className="mt-4 w-full" disabled={busy || arrivals.length < 12} onClick={() => void action(`/admin/rodadas/${round.id}/formacao-inicial`, 'POST', undefined, true)}><Play size={18}/>Formar times</Button>}</article></div>}
      {game && <><div className="mt-5 grid gap-4 lg:grid-cols-3"><TeamCard title="Time 1" players={game.time1} onExit={(id) => action(`/admin/participacoes/${id}/saida`, 'PATCH')} busy={busy}/><TeamCard title="Time 2" players={game.time2} onExit={(id) => action(`/admin/participacoes/${id}/saida`, 'PATCH')} busy={busy}/><TeamCard title="Fila" players={game.fila} queue onExit={(id) => action(`/admin/participacoes/${id}/saida`, 'PATCH')} busy={busy}/></div>{!game.completo && <p className="mt-4 rounded-xl border border-amber-500/30 bg-amber-500/10 p-4 font-bold text-amber-300">Quantidade insuficiente para formar dois times completos.</p>}{round.status === 'EM_ANDAMENTO' && <Link to={`/admin/rodadas/${round.id}/jogo`} className="mt-4 block"><Button className="w-full"><Radio size={18}/>Abrir jogo ao vivo</Button></Link>}</>}
    </>}
  </section>
}

function TeamCard({ title, players, queue = false, onExit, busy }: { title: string; players: EstadoJogo['time1']; queue?: boolean; onExit: (id: string) => Promise<void>; busy: boolean }) {
  return <article className="surface overflow-hidden"><header className="flex items-center justify-between border-b border-white/10 p-4"><span className="flex items-center gap-2 font-black"><Users className="text-brita-500" size={19}/>{title}</span><span className="text-sm font-bold text-neutral-500">{players.length}</span></header><div className="space-y-1 p-3">{players.map((p, index) => <div key={p.participacaoId} className="flex min-h-12 items-center gap-3 rounded-xl px-2 hover:bg-white/[.03]"><span className="w-7 text-center text-sm font-black text-neutral-600">{queue ? index + 1 : '•'}</span><span className="min-w-0 flex-1 truncate font-bold">{p.apelido}</span><button disabled={busy} onClick={() => void onExit(p.participacaoId)} aria-label={`Marcar saída de ${p.apelido}`} className="grid size-11 place-items-center rounded-lg text-neutral-500 hover:text-red-400"><LogOut size={17}/></button></div>)}{!players.length && <EmptyState title="Vazio" description={queue ? 'Ninguém aguardando.' : 'Time incompleto.'}/>}</div></article>
}
