import { ArrowLeft, CircleDot, Pencil, Play, RefreshCw, ShieldCheck, Trash2, Trophy, Users } from 'lucide-react'
import { useCallback, useEffect, useMemo, useState } from 'react'
import { Link, useParams } from 'react-router-dom'
import type { EstadoJogo, GolPartida, JogadorPartida, LadoEquipe, Partida } from '@fut-brita/shared'
import { api } from '../../services/api'
import { Button } from '../../components/ui/Button'
import { EmptyState, ErrorState, Loading } from '../../components/ui/States'
import { Modal } from '../../components/ui/Modal'
import { Toast } from '../../components/ui/Toast'

export function JogoAoVivoPage() {
  const { id } = useParams(); const [match, setMatch] = useState<Partida | null>(null); const [history, setHistory] = useState<Partida[]>([]); const [selectedHistory, setSelectedHistory] = useState<Partida | null>(null); const [game, setGame] = useState<EstadoJogo | null>(null); const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const [goalSide, setGoalSide] = useState<LadoEquipe | null>(null); const [editing, setEditing] = useState<GolPartida | null>(null); const [toast, setToast] = useState<{ message: string; kind?: 'success' | 'error' } | null>(null)
  const load = useCallback(async () => { if (!id) return; try { setError(''); const [current, matches, state] = await Promise.all([api<Partida | null>(`/admin/rodadas/${id}/partidas/atual`), api<Partida[]>(`/admin/rodadas/${id}/partidas`), api<EstadoJogo | null>(`/admin/rodadas/${id}/estado-jogo`)]); setMatch(current); setHistory(matches); setGame(state) } catch (e) { setError(e instanceof Error ? e.message : 'Não foi possível carregar o jogo') } finally { setLoading(false) } }, [id])
  useEffect(() => { void load() }, [load]); useEffect(() => { if (!toast) return; const timer = setTimeout(() => setToast(null), 3000); return () => clearTimeout(timer) }, [toast])
  const mutate = async (path: string, method: string, body?: unknown) => { setBusy(true); try { const updated = await api<Partida>(path, { method, ...(body === undefined ? {} : { body: JSON.stringify(body) }) }); setMatch(updated.status === 'EM_ANDAMENTO' ? updated : null); await load(); return updated } catch (e) { setToast({ message: e instanceof Error ? e.message : 'Ação não concluída', kind: 'error' }); return null } finally { setBusy(false) } }
  const start = async () => { if (!id) return; const created = await mutate(`/admin/rodadas/${id}/partidas/iniciar`, 'POST'); if (created) setToast({ message: `Jogo ${created.numero} iniciado.` }) }
  const scoreGoal = async (player: JogadorPartida) => { if (!match) return; const updated = editing ? await mutate(`/admin/gols/${editing.id}`, 'PATCH', { participacaoId: player.participacaoId, lado: player.lado }) : await mutate(`/admin/partidas/${match.id}/gols`, 'POST', { participacaoId: player.participacaoId, lado: player.lado }); setGoalSide(null); setEditing(null); if (updated) setToast({ message: editing ? `Gol corrigido para ${player.apelido}.` : `⚽ Gol de ${player.apelido}!` }) }
  const finish = async () => { if (!match || !window.confirm(`Time 1 ${match.placarTime1} × ${match.placarTime2} Time 2\n\nFinalizar esta partida?`)) return; const finished = await mutate(`/admin/partidas/${match.id}/finalizar`, 'POST'); if (finished) setToast({ message: finished.resultado === 'EMPATE' ? 'Empate: o time permanente ficou.' : `${finished.timeVencedor === 'TIME_1' ? 'Time 1' : 'Time 2'} venceu e permaneceu.` }) }
  const removeGoal = async (goal: GolPartida) => { if (!window.confirm(`Excluir o gol de ${goal.apelido}?`)) return; const updated = await mutate(`/admin/gols/${goal.id}`, 'DELETE'); if (updated) setToast({ message: 'Gol excluído e placar recalculado.' }) }
  if (loading) return <div className="page-shell py-8"><Loading/></div>
  if (error) return <div className="page-shell py-8"><ErrorState message={error} retry={load}/></div>
  return <div className="page-shell pb-32 pt-5 sm:py-10"><Link to={`/admin/rodadas/${id}`} className="inline-flex min-h-12 items-center gap-2 text-sm font-bold text-neutral-400"><ArrowLeft size={19}/>Voltar para rodada</Link>
    <header className="mt-3 flex items-end justify-between"><div><p className="text-xs font-black uppercase tracking-[.2em] text-brita-500">FUT BRITA</p><h1 className="mt-2 text-3xl font-black">{match ? `Jogo ${match.numero}` : 'Jogo ao vivo'}</h1></div>{match && <span className="rounded-full bg-red-500/10 px-3 py-2 text-xs font-black uppercase text-red-400">● Em andamento</span>}</header>
    {!match ? <section className="mt-6 surface p-6 text-center sm:p-10">{game?.completo ? <><span className="mx-auto grid size-16 place-items-center rounded-2xl bg-brita-500/10 text-brita-500"><Play size={30}/></span><h2 className="mt-5 text-2xl font-black">Próxima partida pronta</h2><p className="mx-auto mt-2 max-w-lg text-neutral-500">Os dois times estão completos. A partida só começa quando você tocar no botão.</p><Button className="mt-6 w-full sm:w-auto" disabled={busy} onClick={() => void start()}>{busy ? 'Iniciando...' : 'Iniciar partida'}</Button></> : <EmptyState title="Times incompletos" description="Complete os dois times antes de iniciar uma partida."/>}</section> : <LiveMatch match={match} busy={busy} onEdit={(goal) => { setEditing(goal); setGoalSide(goal.lado) }} onDelete={removeGoal}/>} 
    {history.length > 0 && <section className="mt-10"><h2 className="text-2xl font-black">Partidas</h2><div className="mt-4 grid gap-3 sm:grid-cols-2 xl:grid-cols-3">{history.map((item) => <button type="button" onClick={() => setSelectedHistory(item)} key={item.id} className="surface min-h-32 p-4 text-left transition hover:border-brita-500"><div className="flex items-center justify-between"><strong>Jogo {item.numero}</strong><span className="text-xs font-bold uppercase text-neutral-500">{item.status === 'FINALIZADA' ? item.resultado : 'Ao vivo'}</span></div><p className="mt-4 text-center text-2xl font-black">{item.placarTime1} <span className="text-neutral-600">×</span> {item.placarTime2}</p><p className="mt-3 text-xs text-neutral-500">Permanente: {item.timePermanente === 'TIME_1' ? 'Time 1' : 'Time 2'} · Entrante: {item.timeEntrante === 'TIME_1' ? 'Time 1' : 'Time 2'}</p></button>)}</div></section>}
    {match && <div className="fixed inset-x-0 bottom-16 z-30 border-t border-white/10 bg-neutral-950/95 p-3 backdrop-blur sm:bottom-0"><div className="mx-auto grid max-w-3xl grid-cols-2 gap-2 sm:grid-cols-3"><Button onClick={() => setGoalSide('TIME_1')} disabled={busy}><CircleDot size={18}/>Gol Time 1</Button><Button onClick={() => setGoalSide('TIME_2')} disabled={busy}><CircleDot size={18}/>Gol Time 2</Button><Button variant="danger" className="col-span-2 sm:col-span-1" onClick={() => void finish()} disabled={busy}>{busy ? <><RefreshCw className="animate-spin" size={18}/>Processando resultado...</> : <><Trophy size={18}/>Finalizar partida</>}</Button></div></div>}
    {(goalSide || editing) && match && <GoalPicker side={goalSide!} match={match} editing={editing} busy={busy} onSelect={scoreGoal} onClose={() => { setGoalSide(null); setEditing(null) }}/>} {selectedHistory && <MatchDetail match={selectedHistory} onClose={() => setSelectedHistory(null)}/>} {toast && <Toast {...toast}/>} 
  </div>
}

function LiveMatch({ match, busy, onEdit, onDelete }: { match: Partida; busy: boolean; onEdit: (goal: GolPartida) => void; onDelete: (goal: GolPartida) => Promise<void> }) {
  const goalCount = useMemo(() => Object.fromEntries([...match.time1, ...match.time2].map((player) => [player.participacaoId, match.gols.filter((goal) => goal.participacaoId === player.participacaoId).length])), [match])
  return <><section className="mt-6 surface overflow-hidden"><div className="grid grid-cols-[1fr_auto_1fr] items-center gap-2 p-5 sm:p-8"><TeamScore label="Time 1" score={match.placarTime1} permanent={match.timePermanente === 'TIME_1'}/><span className="text-3xl font-black text-neutral-700">×</span><TeamScore label="Time 2" score={match.placarTime2} permanent={match.timePermanente === 'TIME_2'}/></div></section><div className="mt-4 grid gap-4 lg:grid-cols-3"><TeamList title="Time 1" players={match.time1} counts={goalCount}/><TeamList title="Time 2" players={match.time2} counts={goalCount}/><TeamList title="Próximos / Fila" players={match.fila} counts={{}} queue/></div><section className="mt-8"><div className="flex items-center justify-between"><h2 className="text-xl font-black">Gols</h2><span className="text-sm text-neutral-500">{match.gols.length} eventos</span></div>{match.gols.length ? <ol className="mt-3 space-y-2">{match.gols.map((goal) => <li key={goal.id} className="surface flex min-h-16 items-center gap-3 px-4"><span className="grid size-9 place-items-center rounded-lg bg-brita-500/10">⚽</span><span className="min-w-0 flex-1"><strong className="block truncate">{goal.apelido}</strong><span className="text-xs text-neutral-500">{goal.lado === 'TIME_1' ? 'Time 1' : 'Time 2'} · Gol {goal.ordem}</span></span><button disabled={busy} onClick={() => onEdit(goal)} className="grid size-11 place-items-center rounded-lg text-neutral-400" aria-label={`Corrigir gol de ${goal.apelido}`}><Pencil size={17}/></button><button disabled={busy} onClick={() => void onDelete(goal)} className="grid size-11 place-items-center rounded-lg text-red-400" aria-label={`Excluir gol de ${goal.apelido}`}><Trash2 size={17}/></button></li>)}</ol> : <p className="mt-3 rounded-xl border border-dashed border-white/10 p-5 text-center text-sm text-neutral-600">Nenhum gol registrado.</p>}</section></>
}
function TeamScore({ label, score, permanent }: { label: string; score: number; permanent: boolean }) { return <div className="min-w-0 text-center"><p className="truncate text-sm font-black uppercase text-neutral-400">{label}</p><p className="mt-2 text-5xl font-black sm:text-7xl">{score}</p><p className={`mt-2 text-[11px] font-bold ${permanent ? 'text-brita-400' : 'text-neutral-500'}`}>{permanent ? '🛡 Vantagem do empate' : '↗ Entrou agora'}</p></div> }
function TeamList({ title, players, counts, queue = false }: { title: string; players: JogadorPartida[]; counts: Record<string, number>; queue?: boolean }) { return <article className="surface overflow-hidden"><header className="flex items-center gap-2 border-b border-white/10 p-4 font-black">{queue ? <Users className="text-brita-500"/> : <ShieldCheck className="text-brita-500"/>}{title}</header><ol className="space-y-1 p-3">{players.map((player, index) => <li key={player.participacaoId} className="flex min-h-12 items-center gap-3 rounded-lg px-2"><span className="w-6 text-center text-sm font-black text-neutral-600">{queue ? index + 1 : '•'}</span><span className="min-w-0 flex-1 truncate font-bold">{player.apelido}</span>{counts[player.participacaoId] > 0 && <span aria-label={`${counts[player.participacaoId]} gols`} className="text-sm">{'⚽'.repeat(counts[player.participacaoId])}</span>}</li>)}</ol></article> }
function GoalPicker({ side, match, editing, busy, onSelect, onClose }: { side: LadoEquipe; match: Partida; editing: GolPartida | null; busy: boolean; onSelect: (player: JogadorPartida) => Promise<void>; onClose: () => void }) { const players = editing ? [...match.time1, ...match.time2] : side === 'TIME_1' ? match.time1 : match.time2; return <Modal title={editing ? 'Corrigir autor do gol' : `Gol do ${side === 'TIME_1' ? 'Time 1' : 'Time 2'}`} onClose={onClose}><p className="mb-4 text-sm text-neutral-500">Toque no jogador que marcou.</p><div className="grid gap-2 sm:grid-cols-2">{players.map((player) => <button key={player.participacaoId} disabled={busy} onClick={() => void onSelect(player)} className="flex min-h-16 items-center gap-3 rounded-xl border border-white/10 px-4 text-left font-black hover:border-brita-500 hover:bg-brita-500/5"><span className="grid size-10 place-items-center rounded-xl bg-brita-500/10">⚽</span><span className="min-w-0"><span className="block truncate">{player.apelido}</span>{editing && <span className="text-xs font-medium text-neutral-500">{player.lado === 'TIME_1' ? 'Time 1' : 'Time 2'}</span>}</span></button>)}</div></Modal> }
function MatchDetail({ match, onClose }: { match: Partida; onClose: () => void }) { return <Modal title={`Jogo ${match.numero} — ${match.placarTime1} × ${match.placarTime2}`} onClose={onClose}><div className="grid gap-4 sm:grid-cols-2"><HistoryTeam title="Time 1" players={match.time1}/><HistoryTeam title="Time 2" players={match.time2}/></div><dl className="mt-5 grid grid-cols-2 gap-3 rounded-xl bg-white/[.03] p-4 text-sm"><div><dt className="text-neutral-500">Resultado</dt><dd className="mt-1 font-black">{match.resultado ?? 'Em andamento'}</dd></div><div><dt className="text-neutral-500">Vantagem</dt><dd className="mt-1 font-black">{match.timePermanente === 'TIME_1' ? 'Time 1' : 'Time 2'}</dd></div><div><dt className="text-neutral-500">Entrante</dt><dd className="mt-1 font-black">{match.timeEntrante === 'TIME_1' ? 'Time 1' : 'Time 2'}</dd></div><div><dt className="text-neutral-500">Time que saiu</dt><dd className="mt-1 font-black">{match.timeSaiu ? (match.timeSaiu === 'TIME_1' ? 'Time 1' : 'Time 2') : '—'}</dd></div></dl><h3 className="mt-5 font-black">Gols</h3><ol className="mt-2 space-y-2">{match.gols.length ? match.gols.map((goal) => <li key={goal.id} className="rounded-lg border border-white/10 p-3 text-sm"><strong>⚽ {goal.apelido}</strong><span className="text-neutral-500"> · {goal.lado === 'TIME_1' ? 'Time 1' : 'Time 2'}</span></li>) : <li className="text-sm text-neutral-500">Partida sem gols.</li>}</ol></Modal> }
function HistoryTeam({ title, players }: { title: string; players: JogadorPartida[] }) { return <div><h3 className="text-xs font-black uppercase text-neutral-500">{title}</h3><ul className="mt-2 space-y-1 text-sm">{players.map((player) => <li key={player.participacaoId} className="truncate font-bold">{player.apelido}</li>)}</ul></div> }
