import { ArrowLeft, Goal, Medal, Trophy, Users } from 'lucide-react'
import { useEffect, useState } from 'react'
import { Link, useParams } from 'react-router-dom'
import type { ResumoRodadaPublica } from '@fut-brita/shared'
import { api } from '../../services/api'
import { ErrorState, Loading } from '../../components/ui/States'
import { dateBr } from '../../utils/format'

export function HistoricoDetailPage() { const { id } = useParams(); const [round, setRound] = useState<ResumoRodadaPublica | null>(null); const [error, setError] = useState(''); useEffect(() => { if (id) api<ResumoRodadaPublica>(`/public/historico/${id}`).then(setRound).catch((e) => setError(e instanceof Error ? e.message : 'Rodada não encontrada')) }, [id]); if (error) return <section className="page-shell py-10"><ErrorState message={error}/></section>; if (!round) return <Loading/>; return <section className="page-shell py-8 sm:py-14"><Link to="/historico" className="inline-flex min-h-12 items-center gap-2 font-bold text-neutral-400"><ArrowLeft size={18}/>Histórico</Link><p className="mt-4 text-xs font-black uppercase tracking-[.2em] text-brita-500">Rodada encerrada</p><h1 className="mt-2 text-3xl font-black capitalize sm:text-5xl">{dateBr(round.data)}</h1><div className="mt-6 grid grid-cols-2 gap-3 sm:grid-cols-4"><Metric value={round.participantes} label="Participantes"/><Metric value={round.partidas} label="Partidas"/><Metric value={round.gols} label="Gols"/><Metric value={round.goleiros} label="Goleiros"/></div><section className="mt-9"><h2 className="flex items-center gap-2 text-2xl font-black"><Medal className="text-brita-500"/>Destaques</h2><div className="mt-4 grid gap-3 sm:grid-cols-3"><Highlight icon={Goal} title="Artilheiro da noite" player={round.destaques.artilheiro?.jogador.apelido} value={round.destaques.artilheiro ? `${round.destaques.artilheiro.gols} gols` : undefined}/><Highlight icon={Trophy} title="Mais vitórias" player={round.destaques.maisVitorias?.jogador.apelido} value={round.destaques.maisVitorias ? `${round.destaques.maisVitorias.vitorias} vitórias` : undefined}/><Highlight icon={Users} title="Mais jogos" player={round.destaques.maisJogos?.jogador.apelido} value={round.destaques.maisJogos ? `${round.destaques.maisJogos.partidas} jogos` : undefined}/></div></section><section className="mt-10"><h2 className="text-2xl font-black">Sequência das partidas</h2><div className="mt-4 space-y-4">{round.jogos.map((game) => <article key={game.id} className="surface overflow-hidden"><header className="flex items-center justify-between border-b border-white/10 p-4"><strong>Jogo {game.numero}</strong><span className="text-xs font-black uppercase text-neutral-500">{game.resultado}</span></header><div className="grid grid-cols-[1fr_auto_1fr] items-center gap-3 p-5 text-center"><Team label="Time 1" players={game.time1.map((item) => item.apelido)} score={game.placarTime1}/><span className="text-2xl font-black text-neutral-600">×</span><Team label="Time 2" players={game.time2.map((item) => item.apelido)} score={game.placarTime2}/></div><div className="border-t border-white/10 p-4"><h3 className="text-xs font-black uppercase text-neutral-500">Gols</h3><p className="mt-2 text-sm font-bold">{game.gols.length ? game.gols.map((goal) => `⚽ ${goal.apelido}`).join(' · ') : 'Partida sem gols'}</p></div></article>)}</div></section></section> }
function Metric({ value, label }: { value: number; label: string }) { return <div className="surface p-4"><strong className="text-3xl font-black text-brita-500">{value}</strong><span className="mt-1 block text-sm text-neutral-500">{label}</span></div> }
function Highlight({ icon: Icon, title, player, value }: { icon: typeof Goal; title: string; player?: string; value?: string }) { return <div className="surface p-5"><Icon className="text-brita-500"/><span className="mt-4 block text-xs font-black uppercase text-neutral-500">{title}</span><strong className="mt-1 block text-xl">{player ?? 'Sem dados'}</strong>{value && <span className="text-sm text-brita-400">{value}</span>}</div> }
function Team({ label, players, score }: { label: string; players: string[]; score: number }) { return <div className="min-w-0"><span className="text-xs font-black uppercase text-neutral-500">{label}</span><strong className="my-2 block text-4xl">{score}</strong><span className="block truncate text-xs text-neutral-600">{players.join(', ')}</span></div> }
