import { ArrowRight, CalendarDays, Goal, Shield, Users } from 'lucide-react'
import { useEffect, useState } from 'react'
import { Link } from 'react-router-dom'
import type { HistoricoRodadaItem } from '@fut-brita/shared'
import { api } from '../../services/api'
import { EmptyState, ErrorState, Loading } from '../../components/ui/States'
import { shortDate } from '../../utils/format'

export function HistoricoPage() { const [rounds, setRounds] = useState<HistoricoRodadaItem[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); useEffect(() => { api<HistoricoRodadaItem[]>('/public/historico').then(setRounds).catch((e) => setError(e instanceof Error ? e.message : 'Não foi possível carregar o histórico')).finally(() => setLoading(false)) }, []); return <section className="page-shell min-h-[75svh] py-8 sm:py-14"><p className="text-xs font-black uppercase tracking-[.2em] text-brita-500">Memória do Fut</p><h1 className="mt-2 text-4xl font-black sm:text-5xl">Histórico de rodadas</h1><p className="mt-3 text-neutral-400">Placares, gols e destaques de cada quarta-feira encerrada.</p>{loading ? <Loading/> : error ? <div className="mt-6"><ErrorState message={error}/></div> : !rounds.length ? <div className="mt-7"><EmptyState title="Nenhuma rodada encerrada" description="O histórico será criado automaticamente após o encerramento das rodadas."/></div> : <div className="mt-7 grid gap-4 md:grid-cols-2">{rounds.map((round) => <Link key={round.id} to={`/historico/${round.id}`} className="surface p-5 transition hover:border-brita-500/40"><div className="flex items-start justify-between gap-3"><span className="grid size-12 place-items-center rounded-2xl bg-brita-500/10 text-brita-500"><CalendarDays/></span><ArrowRight className="text-neutral-600"/></div><h2 className="mt-5 text-2xl font-black">{shortDate(round.data)}</h2><div className="mt-5 grid grid-cols-2 gap-3 text-sm"><Fact icon={Users} value={round.participantes} label="participantes"/><Fact icon={Shield} value={round.partidas} label="partidas"/><Fact icon={Goal} value={round.gols} label="gols"/><Fact icon={Users} value={round.goleiros} label="goleiros"/></div></Link>)}</div>}</section> }
function Fact({ icon: Icon, value, label }: { icon: typeof Users; value: number; label: string }) { return <span className="flex items-center gap-2 text-neutral-400"><Icon size={16} className="text-brita-500"/><strong className="text-white">{value}</strong> {label}</span> }
