import { ArrowRight, Clock3, History, Trophy, Users } from 'lucide-react'
import { Link } from 'react-router-dom'

const modules = [
  { name: 'Rodada', text: 'A próxima quarta começa aqui.', icon: Clock3, soon: true },
  { name: 'Rankings', text: 'Desempenho e disputa saudável.', icon: Trophy, soon: true },
  { name: 'Jogadores', text: 'Conheça quem joga com a gente.', icon: Users, href: '/jogadores' },
  { name: 'Histórico', text: 'As memórias de cada partida.', icon: History, soon: true },
]
export function HomePage() { return <><section className="page-shell flex min-h-[68svh] items-center py-14 sm:py-20"><div className="max-w-3xl"><div className="mb-5 inline-flex items-center gap-2 rounded-full border border-brita-500/30 bg-brita-500/10 px-4 py-2 text-xs font-bold uppercase tracking-[.18em] text-brita-400"><span className="size-2 rounded-full bg-brita-500" />Toda quarta tem jogo</div><h1 className="max-w-2xl text-5xl font-black leading-[.92] tracking-[-.055em] text-white sm:text-7xl lg:text-8xl">A pelada mais <span className="text-brita-500">brita</span> da vila.</h1><p className="mt-6 max-w-xl text-lg leading-relaxed text-neutral-400 sm:text-xl">Organização simples, resenha garantida e futebol toda semana. O ponto de encontro da nossa turma.</p><Link to="/jogadores" className="mt-8 inline-flex min-h-14 w-full items-center justify-center gap-2 rounded-2xl bg-brita-500 px-6 font-extrabold text-black shadow-glow transition hover:bg-brita-400 sm:w-auto">Ver jogadores <ArrowRight size={20} /></Link></div></section><section className="page-shell pb-20"><div className="mb-7"><span className="text-xs font-bold uppercase tracking-[.2em] text-brita-500">No Fut Brita</span><h2 className="mt-2 text-2xl font-extrabold sm:text-3xl">Tudo em um só lugar</h2></div><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{modules.map(({ name, text, icon: Icon, href, soon }) => { const content = <><div className="mb-6 flex items-start justify-between"><span className="grid size-12 place-items-center rounded-2xl bg-brita-500/10 text-brita-500"><Icon /></span>{soon && <span className="rounded-full border border-white/10 px-3 py-1 text-[10px] font-bold uppercase tracking-wider text-neutral-500">Em breve</span>}</div><h3 className="text-lg font-extrabold">{name}</h3><p className="mt-2 text-sm leading-relaxed text-neutral-500">{text}</p></>; return href ? <Link key={name} to={href} className="surface min-h-48 p-5 transition hover:-translate-y-1 hover:border-brita-500/30">{content}</Link> : <article key={name} className="surface min-h-48 p-5 opacity-75">{content}</article> })}</div></section></> }
