import { CalendarDays, Goal, ListOrdered, ShieldCheck, UserRound, Users } from 'lucide-react'
import { useCallback, useEffect, useMemo, useState } from 'react'
import type { EstadoJogo, Partida, RodadaPublica } from '@fut-brita/shared'
import { api } from '../../services/api'
import { EmptyState, ErrorState, Loading } from '../../components/ui/States'
import { dateBr, statusClass, statusLabel } from '../../utils/format'

export function RodadaPublicaPage() {
  const [round, setRound] = useState<RodadaPublica | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState('')
  const load = useCallback(async () => { setLoading(true); setError(''); try { setRound(await api('/public/rodadas/atual')) } catch (e) { setError(e instanceof Error ? e.message : 'Não foi possível carregar a rodada') } finally { setLoading(false) } }, [])
  useEffect(() => { void load() }, [load])
  useEffect(() => { const timer = setInterval(() => void load(), 10_000); return () => clearInterval(timer) }, [load])
  const line = useMemo(() => round?.participacoes.filter((p) => p.tipo === 'LINHA') ?? [], [round]); const goalkeepers = useMemo(() => round?.participacoes.filter((p) => p.tipo === 'GOLEIRO') ?? [], [round])
  const participants = (items: RodadaPublica['participacoes']) => <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{items.map((p) => <article key={p.id} className="surface flex min-h-20 items-center gap-3 p-4"><span className="grid size-11 shrink-0 place-items-center rounded-xl bg-brita-500/10 text-brita-500"><UserRound size={21}/></span><span className="min-w-0"><strong className="block truncate">{p.jogador.apelido}</strong><span className="block truncate text-sm text-neutral-500">{p.jogador.nome}</span></span></article>)}</div>
  return <section className="page-shell min-h-[75svh] py-10 sm:py-16">{loading ? <Loading/> : error ? <ErrorState message={error} retry={load}/> : !round ? <EmptyState title="Sem rodada atual" description="A próxima rodada aparecerá aqui quando for planejada."/> : <><div className="surface overflow-hidden"><div className="border-b border-white/10 bg-brita-500/5 p-5 sm:p-8"><div className="flex flex-wrap items-center gap-3"><span className={`rounded-full px-3 py-1 text-xs font-bold uppercase ${statusClass[round.status]}`}>{statusLabel[round.status]}</span><span className="inline-flex items-center gap-2 text-sm text-neutral-400"><CalendarDays size={17}/>{round.horario}</span></div><h1 className="mt-5 max-w-3xl text-3xl font-black capitalize tracking-tight sm:text-5xl">{dateBr(round.data)}</h1><p className="mt-3 text-neutral-500">Participantes e formação atual do Fut Brita.</p></div></div>
    {round.partidaAtual && <PublicLiveMatch match={round.partidaAtual}/>} {round.estadoJogo && <PublicGame game={round.estadoJogo}/>}<div className="mt-9 space-y-10"><section><div className="mb-4 flex items-center gap-3"><Goal className="text-brita-500"/><h2 className="text-xl font-extrabold">Jogadores de linha <span className="text-neutral-600">({line.length})</span></h2></div>{line.length ? participants(line) : <p className="text-sm text-neutral-600">Nenhum jogador de linha adicionado.</p>}</section><section><div className="mb-4 flex items-center gap-3"><ShieldCheck className="text-brita-500"/><h2 className="text-xl font-extrabold">Goleiros <span className="text-neutral-600">({goalkeepers.length})</span></h2></div>{goalkeepers.length ? participants(goalkeepers) : <p className="text-sm text-neutral-600">Nenhum goleiro adicionado.</p>}</section></div></>}</section>
}

function PublicLiveMatch({ match }: { match: Partida }) {
  const goals = (side: 'TIME_1' | 'TIME_2') => match.gols.filter((goal) => goal.lado === side)
  return <section className="mt-9 surface overflow-hidden"><header className="border-b border-white/10 bg-red-500/5 p-4 sm:p-6"><div className="flex items-center justify-between"><div><p className="text-xs font-black uppercase tracking-[.18em] text-red-400">● Jogo atual</p><h2 className="mt-2 text-2xl font-black">Jogo {match.numero}</h2></div><button onClick={() => window.location.reload()} className="min-h-11 rounded-xl border border-white/10 px-4 text-sm font-bold text-neutral-400">Atualizar</button></div></header><div className="grid grid-cols-[1fr_auto_1fr] items-center gap-2 p-5 sm:p-8"><PublicScore label="Time 1" score={match.placarTime1} permanent={match.timePermanente === 'TIME_1'}/><span className="text-3xl font-black text-neutral-700">×</span><PublicScore label="Time 2" score={match.placarTime2} permanent={match.timePermanente === 'TIME_2'}/></div>{match.gols.length > 0 && <div className="grid gap-3 border-t border-white/10 p-4 sm:grid-cols-2"><GoalSummary title="Gols Time 1" goals={goals('TIME_1')}/><GoalSummary title="Gols Time 2" goals={goals('TIME_2')}/></div>}</section>
}
function PublicScore({ label, score, permanent }: { label: string; score: number; permanent: boolean }) { return <div className="min-w-0 text-center"><p className="truncate text-sm font-black uppercase text-neutral-400">{label}</p><p className="mt-2 text-5xl font-black sm:text-7xl">{score}</p><p className={`mt-2 text-[11px] font-bold ${permanent ? 'text-brita-400' : 'text-neutral-500'}`}>{permanent ? '🛡 Vantagem do empate' : '↗ Entrante'}</p></div> }
function GoalSummary({ title, goals }: { title: string; goals: Partida['gols'] }) { return <div><h3 className="text-xs font-black uppercase text-neutral-500">{title}</h3><p className="mt-2 text-sm font-bold">{goals.length ? goals.map((goal) => `⚽ ${goal.apelido}`).join(' · ') : 'Nenhum'}</p></div> }

function PublicGame({ game }: { game: EstadoJogo }) {
  const card = (title: string, items: EstadoJogo['time1'], queue = false) => <article className="surface overflow-hidden"><header className="flex items-center gap-2 border-b border-white/10 p-4 font-black">{queue ? <ListOrdered className="text-brita-500"/> : <Users className="text-brita-500"/>}{title}</header><ol className="space-y-1 p-3">{items.map((p, index) => <li key={p.participacaoId} className="flex min-h-11 items-center gap-3 rounded-lg px-2"><span className="w-6 text-center text-sm font-black text-neutral-600">{queue ? index + 1 : '•'}</span><span className="truncate font-bold">{p.apelido}</span></li>)}</ol></article>
  return <section className="mt-9"><div className="flex items-end justify-between"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-brita-500">EM CAMPO</p><h2 className="mt-2 text-2xl font-black">Formação atual</h2></div><span className="text-sm font-bold text-neutral-500">Ciclo {game.ciclo}</span></div><div className="mt-4 grid gap-4 lg:grid-cols-3">{card('Time 1', game.time1)}{card('Time 2', game.time2)}{card('Fila', game.fila, true)}</div></section>
}
