import { CalendarDays, Home, LogOut, Menu, Users, X } from 'lucide-react'
import { useState } from 'react'
import { NavLink, Outlet, useNavigate } from 'react-router-dom'
import { useAuth } from '../features/auth/AuthContext'
import { Button } from '../components/ui/Button'

export function AdminLayout() {
  const { admin, logout } = useAuth()
  const navigate = useNavigate()
  const [open, setOpen] = useState(false)
  const exit = async () => { await logout(); navigate('/admin/login', { replace: true }) }
  const navClass = ({ isActive }: { isActive: boolean }) => `flex min-h-12 items-center gap-3 rounded-xl px-4 font-bold transition ${isActive ? 'bg-brita-500 text-black' : 'text-neutral-400 hover:bg-white/5 hover:text-white'}`
  const sidebar = <><div className="mb-8 flex items-center gap-3"><img src="/pwa-192.png" alt="" className="size-11 rounded-xl object-cover"/><div><strong className="block leading-tight">FUT BRITA</strong><span className="text-xs text-neutral-500">Administração</span></div></div><nav className="space-y-2"><NavLink to="/admin" end className={navClass} onClick={() => setOpen(false)}><Home size={20}/>Visão geral</NavLink><NavLink to="/admin/rodadas" className={navClass} onClick={() => setOpen(false)}><CalendarDays size={20}/>Rodadas</NavLink><NavLink to="/admin/jogadores" className={navClass} onClick={() => setOpen(false)}><Users size={20}/>Jogadores</NavLink></nav><div className="mt-auto border-t border-white/10 pt-5"><p className="mb-3 truncate text-sm text-neutral-400">{admin?.nome}</p><Button variant="ghost" className="w-full justify-start" onClick={exit}><LogOut size={19}/>Sair</Button></div></>
  return <div className="min-h-svh overflow-x-hidden bg-neutral-950 text-white"><aside className="fixed inset-y-0 left-0 z-40 hidden w-64 flex-col border-r border-white/10 bg-neutral-900 p-5 md:flex">{sidebar}</aside>{open && <div className="fixed inset-0 z-50 bg-black/70 md:hidden" onMouseDown={(event) => event.target === event.currentTarget && setOpen(false)}><aside className="flex h-full w-[min(82vw,320px)] flex-col bg-neutral-900 p-5"><button onClick={() => setOpen(false)} className="absolute right-4 top-3 grid size-12 place-items-center" aria-label="Fechar menu"><X/></button>{sidebar}</aside></div>}<header className="sticky top-0 z-30 flex h-16 items-center justify-between border-b border-white/10 bg-neutral-950/95 px-4 backdrop-blur md:hidden"><button onClick={() => setOpen(true)} className="grid size-12 place-items-center rounded-xl" aria-label="Abrir menu"><Menu/></button><strong className="text-sm tracking-wide">PAINEL FUT BRITA</strong><span className="size-12"/></header><main className="min-w-0 pb-24 md:ml-64 md:pb-8"><Outlet/></main><nav className="fixed inset-x-0 bottom-0 z-30 grid grid-cols-3 border-t border-white/10 bg-neutral-900/95 px-2 pb-[max(.5rem,env(safe-area-inset-bottom))] pt-2 backdrop-blur md:hidden"><NavLink to="/admin" end className={navClass}><Home size={18}/><span className="sr-only sm:not-sr-only">Início</span></NavLink><NavLink to="/admin/rodadas" className={navClass}><CalendarDays size={18}/><span className="sr-only sm:not-sr-only">Rodadas</span></NavLink><NavLink to="/admin/jogadores" className={navClass}><Users size={18}/><span className="sr-only sm:not-sr-only">Jogadores</span></NavLink></nav></div>
}
